# Generated by Django 4.0.3 on 2022-06-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculartor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.IntegerField()),
                ('wage', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('holiday_pay', models.IntegerField()),
                ('overtime_pay', models.IntegerField()),
            ],
        ),
    ]
