# Generated by Django 4.0.3 on 2022-06-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_suggestioncommnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('writer', models.CharField(max_length=10)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='suggestioncommnet',
            name='notice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.suggestion'),
        ),
        migrations.DeleteModel(
            name='SuggestionBox',
        ),
    ]
